name: ${project.artifactId}
main: es.meriland.chat.bukkit.BukkitPlugin
version: ${project.version}
author: Cadiducho
depend: [Vault]
commands:
    tell:
        aliases: ["w", "m", "msg"]
    r:
        aliases: ["reply"]
    ignore:
        aliases: ["ignora", "ignorar"]